[phases.setup]
packages = ["python310", "python310Packages.pip", "gcc"]

[phases.build]
command = "python3 -m pip install --upgrade pip setuptools wheel && python3 -m pip install -r requirements.txt"

[phases.start]
command = "python3 app.py"
