[phases.setup]
packages = ["python312", "python312Packages.pip", "gcc"]

[phases.build]
command = """
python3.12 -m pip install --upgrade pip setuptools wheel
python3.12 -m pip install -r requirements.txt
"""

[phases.start]
command = "python3.12 app.py"
