[phases.setup]
packages = ["python37", "python37Packages.pip", "gcc"]

[phases.build]
command = """
python3.7 -m pip install --upgrade pip setuptools wheel
python3.7 -m pip install -r requirements.txt
"""

[phases.start]
command = "python3.7 app.py"
